// <auto-generated by fixture-embed> 内嵌自 evidence/fixtures/proxy-targets.tsv（新鲜反编译提取，2026-08-26）。
// 目的：让测试完全自包含，不依赖仓库外的 evidence/ 大文件。
namespace AbyssCGUnlock.Tests;

internal static class ProxyTargetsFixture
{
    internal const string Text = """
# 新鲜代理程序集(Project.dll)元数据夹具 —— 由 evidence/dump/types.tsv + members.tsv + ISIL 提取
# 提取: docker run --rm -v evidence:/e:ro debian:bookworm-slim grep ... (2026-08-26)

## 类型（types.tsv 原文）
class	Project.Interaction.AdventurerDetail.R18StoryListViewController	base=Project.Common.Scroller.SimpleListViewServiceBase`1[[Project.Interaction.AdventurerDetail.StoryListPictThumbnail, Project, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]
class	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	base=Il2CppSystem.Object
class	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	base=UnityEngine.MonoBehaviour
class	Project.Interaction.AdventurerDetail.StoryListThumbnailModel	base=Il2CppSystem.Object
enum	Project.Master.NovelType	base=System.Enum

## 成员（members.tsv 原文，注意代理名称已被改写）
M	Project.Interaction.AdventurerDetail.R18StoryListViewController	UpdateListView(Il2CppSystem.Collections.Generic.IEnumerable`1[[Project.Master.NoaMessagePack.MNovelCharacters, Project, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]],Il2CppSystem.Collections.Generic.IEnumerable`1[[Project.Master.NoaMessagePack.MNovelCharacterSkins, Project, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]],System.Int32,Il2CppSystem.Collections.Generic.List`1[[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],System.Boolean) -> System.Void
M	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	UpdateView(Project.Interaction.AdventurerDetail.StoryListThumbnailModel) -> System.Void
P	Project.Interaction.AdventurerDetail.StoryListThumbnailModel	_IsExistStory_k__BackingField : System.Boolean
P	Project.Interaction.AdventurerDetail.StoryListThumbnailModel	_IsNtr_k__BackingField : System.Boolean
P	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	_coverObject : UnityEngine.GameObject
P	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	_coverText : TMPro.TMP_Text
P	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	_ntrBlockObject : UnityEngine.GameObject
M	Project.Interaction.AdventurerDetail.StoryListThumbnailModel	get_NovelType() -> Project.Master.NovelType
M	Project.Interaction.AdventurerDetail.R18StoryListViewController	get_ActiveModels() -> Il2CppSystem.Collections.Generic.IReadOnlyList`1[[Project.Interaction.AdventurerDetail.StoryListThumbnailModel, Project, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]

## NovelType 枚举成员（members.tsv）
F	Project.Master.NovelType	None : Project.Master.NovelType
F	Project.Master.NovelType	Main : Project.Master.NovelType
F	Project.Master.NovelType	Event : Project.Master.NovelType
F	Project.Master.NovelType	Character : Project.Master.NovelType
F	Project.Master.NovelType	Home : Project.Master.NovelType
F	Project.Master.NovelType	CharacterSkin : Project.Master.NovelType
F	Project.Master.NovelType	Prologue : Project.Master.NovelType
F	Project.Master.NovelType	Other : Project.Master.NovelType
## ISIL 证据: 构造器 NovelType 赋值
ISIL StoryListThumbnailModel.txt:235 Move NovelType,3 (MNovelCharacters 构造器)
ISIL StoryListThumbnailModel.txt:423 Move NovelType,5 (MNovelCharacterSkins 构造器)
## 闭包方法在代理程序集里的真实（改写后）名字
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	_UpdateListView_b__0(Project.Master.NoaMessagePack.MNovelCharacters) -> Project.Interaction.AdventurerDetail.StoryListThumbnailModel
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	_UpdateListView_b__1(Project.Master.NoaMessagePack.MNovelCharacterSkins) -> Project.Interaction.AdventurerDetail.StoryListThumbnailModel
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	get_intimacyLevel() -> System.Int32
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	set_intimacyLevel(System.Int32) -> System.Void
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	get___4__this() -> Project.Interaction.AdventurerDetail.R18StoryListViewController
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	set___4__this(Project.Interaction.AdventurerDetail.R18StoryListViewController) -> System.Void
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	get_userSkinIds() -> Il2CppSystem.Collections.Generic.List`1[[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	set_userSkinIds(Il2CppSystem.Collections.Generic.List`1[[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]) -> System.Void
## 代理程序集类型声明可见性（ilspycmd 反编译原文）
public sealed class __c__DisplayClass11_0 : Il2CppSystem.Object  [ObfuscatedName(...

## 190103/190108 服务端校验证据（2026-08-26 追加）
# 播放确认后的服务端请求（ISIL ConfirmNovelFlashbackPopupController_NestedType___TransitionNovelScene_b__16_0_d.txt:392）
Call NovelApiDataStore.RequestAsync, NovelReadResponseEntity, this._novelType, this._novelId
# 错误码展示层（ISIL ApiErrorMessageBuilder.txt:554）
String.Format, Error: エラーが発生しました。Error Code: {0}, errorCode
# 错误码映射（dump types.tsv/members.tsv）
class  Project.Api.ServerErrorCode  (ServerErrorCodeMap: Dictionary Int32,String)
M  Project.Api.NovelApiDataStore  RequestAsync(Project.Master.NovelType,System.Int64,Il2CppSystem.Threading.CancellationToken)
F  Project.Api.NovelApiDataStore  NativeMethodInfoPtr_RequestAsync_Public_Static_UniTask_1_NovelReadResponseEntity_NovelType_Int64_CancellationToken_0
class  Project.Api.NovelReadResponseEntity  base=Project.Api.AppContentsEntityBase
P  Project.Api.NovelReadResponseEntity  read_rewards
class  Project.Api.RecordEntity / Project.Api.NotifyEntity  (AppContentsEntityBase.records/notifies)
# ui_misc 主数据文本（AbyssMod dump，只读）
逆夜袭玩法套餐 / Error Code: 190108
和老师一起的培训 / Error Code: 190103

## 角色详情纯本地解锁接缝（Project.dll 代理源码 + ISIL，2026-08-26）
class Project.Interaction.CharacterList.SubService+__c
M Project.Interaction.CharacterList.SubService+__c _SetupCharacterListEvent_b__33_0(CharacterInteractionThumbnailModel,SubService) -> System.Void
M Project.Interaction.CharacterList.SubService CreateCharacterThumbnailModels() -> Il2CppSystem.Collections.Generic.IReadOnlyList<CharacterInteractionThumbnailModel>
P Project.Interaction.CharacterList.SubService _nonHasCharaDataList : Il2CppSystem.Collections.Generic.IReadOnlyList<CharacterData>
P Project.Interaction.CharacterList.SubService _userData : Project.User.UserData
class Project.Interaction.AdventurerDetail.SubService+__c__DisplayClass90_0
M Project.Interaction.AdventurerDetail.SubService+__c__DisplayClass90_0 _InitializeViewAsync_b__6(UniRx.Unit,SubService,UnityEngine.GameObject) -> System.Void
P Project.User.CharacterData _IsTavernRegistered_k__BackingField : System.Boolean
P Project.User.UserData _CharaDataStore_k__BackingField : Project.User.CharacterDataStore
P Project.User.CharacterDataStore _dataList : Il2CppSystem.Collections.Generic.List<CharacterData>
class Project.User.CharacterDataStore
M Project.User.CharacterDataStore GetByTableId(System.Int64) -> Project.User.CharacterData

## 队伍角色页与主角色详情接缝（Project.dll 代理源码 + ISIL，2026-08-26）
class Project.CharacterTop.SubService
M Project.CharacterTop.SubService UpdateView() -> System.Void
M Project.CharacterTop.CharacterTopCharacterThumbnailModel CharacterTopCharacterThumbnailModel(System.Int64,Il2CppSystem.Threading.CancellationToken) -> System.Void
class Project.CharacterTop.SubScene+_OnRefreshAsync_d__10
P Project.CharacterTop.SubScene+_OnRefreshAsync_d__10 __1__state : System.Int32
M Project.CharacterTop.SubScene+_OnRefreshAsync_d__10 MoveNext() -> System.Void
M Project.CharacterTop.CharacterListWithFavoriteViewController RefreshActiveCharacterList() -> System.Void
class Project.CharacterDetail.SubService
# 崩溃证据：不要 patch 此复杂值类型签名；ErrorLog 显示 Harmony trampoline 在 il2cpp_value_box 访问冲突
M Project.CharacterDetail.SubService UpdateCurrentCharacterModel(System.Int64,System.Boolean,Il2CppSystem.Threading.CancellationToken,Il2CppSystem.Nullable<CharacterInfoBoxGroupViewService.TabType>,Il2CppSystem.Nullable<CharacterMasteryTabIndex>,System.Boolean) -> System.Void
class Project.Master.NoaMessagePack.MCharacters
F Project.Master.NoaMessagePack.MCharacters id : System.Int64
F Project.Master.NoaMessagePack.MCharacters open_at : System.String
class Project.Master.MasterDataStore
M Project.Master.MasterDataStore GetCache<T>() -> Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppArrayBase<T>
interface Absf.IServerTimeAccessor
P Absf.IServerTimeAccessor NowTime : Il2CppSystem.DateTime
M Project.DateTimeExtensions IsBetween(Il2CppSystem.DateTime,System.String,System.String) -> System.Boolean
P Project.User.CharacterData MCharaId : System.Int64
M Project.User.CharacterDataStore CreateFromMaster(System.Int64,System.Int32,System.Int32) -> Project.User.CharacterData

## CharacterTop 延迟缩略图稳定性接缝（Project.dll 代理源码 + ISIL，2026-08-26）
class Project.Outgame.CharacterModel
M Project.Outgame.CharacterModel CreateFromUser(System.Int64,Project.AppDefine+IconSize,Il2CppSystem.Threading.CancellationToken) -> Project.Outgame.CharacterModel
M Project.Outgame.CharacterModel CreateFromMaster(Project.User.CharacterData,Project.AppDefine+IconSize,Il2CppSystem.Threading.CancellationToken) -> Project.Outgame.CharacterModel
# CharacterTop 构造器固定走 User 模型；User/Master 两个工厂只在 isMaster 参数上分流
ISIL CharacterTopCharacterThumbnailModel.txt:554 Call CharacterModel.CreateFromUser
ISIL CharacterModel.txt:1959 Call CharacterModel..ctor(..., isMaster=0, ...)
ISIL CharacterModel.txt:2437 Call CharacterModel..ctor(..., isMaster=1, ...)
# User 路径延迟执行时重查账号角色列表并直接解引用；Master 路径只查下载主数据皮肤缓存
ISIL CharacterThumbnailLoader_LoadThumbnailFromUserDataAsync:389 FirstSafe(CharacterData predicate)
ISIL CharacterThumbnailLoader_LoadThumbnailFromUserDataAsync:414/427 dereference CharacterData skin ids
ISIL CharacterThumbnailLoader_LoadThumbnailFromMasterDataAsync:321 MRecordCache<MCharacterSkins,(Int64,Int32)>.Get
ISIL LazyLoadThumbnail_FetchAsync:260 AsyncLazy<Sprite>.GetAwaiter

## 未持有角色交流页 Tavern 皮肤映射接缝（Project.dll 代理元数据 + ISIL，2026-08-26）
class Project.Master.NoaMessagePack.MCharacterSkins
P Project.Master.NoaMessagePack.MCharacterSkins id : System.Int64
P Project.Master.NoaMessagePack.MCharacterSkins m_character_id : System.Int64
P Project.Master.NoaMessagePack.MCharacterSkins type : System.Int32
P Project.Master.NoaMessagePack.MCharacterSkins is_default : System.Int32
P Project.Master.NoaMessagePack.MCharacterSkins asset_id : System.String
P Project.User.CharacterData _TavernMCharacterSkinId_k__BackingField : System.Int64
# CharacterData.Apply(long) 选择 type=1/is_default=1 的默认皮肤，却不设置 Tavern 字段
ISIL CharacterData.txt:1825-1860 GetCache<MCharacterSkins> + FirstSafe + AssetId/VoiceAssetId
# 交流页直接把该字段传入 TavernUtility；工具按 MCharacterSkins.id 精确 FirstSafe
ISIL AdventurerDetail_SubService_UpdateView_d__101.txt:1623 GetTavernAssetIdFromMSkinId(TavernMCharacterSkinId)
ISIL TavernUtility.txt:3256-3287 FirstSafe(MCharacterSkins.id == tavernMCharacterSkinId) -> asset_id

## 未持有角色 Tavern 卡片与工作皮肤配对接缝（Project.dll 代理元数据 + ISIL + 当前下载 Master，2026-08-26）
class Project.Master.NoaMessagePack.MTavernCharacterCards
P Project.Master.NoaMessagePack.MTavernCharacterCards id : System.Int64
P Project.Master.NoaMessagePack.MTavernCharacterCards m_character_id : System.Int64
P Project.Master.NoaMessagePack.MTavernCharacterCards m_character_skin_id : System.Int64
# UpdateView 的卡片谓词只有角色 ID 与 Tavern 皮肤 ID 两项
ISIL AdventurerDetail_SubService_DisplayClass101_0.txt:352 card.m_character_id == CharacterData.MCharaId
ISIL AdventurerDetail_SubService_DisplayClass101_0.txt:389 card.m_character_skin_id == CharacterData.TavernMCharacterSkinId
# 当前下载 MessagePack Master：68 个角色全部有卡片；69 条卡片全部引用现存皮肤
CACHE m_tavern_character_cards characters=68 rows=69 missing_character=0 missing_skin=0
CACHE card-backed skin distribution type=2,is_default=1:68; type=2,is_default=2:1
CACHE character=1300014 ordinary_default_skin=130001401 tavern_default_skin=130001402

## 未持有角色只读技能、普通个人剧情、个人资料演出接缝（代理源码 + ISIL，2026-08-26）
M Project.Common.CharacterDetailModel	CreateFromUserData(Project.Master.MasterDataStore,Project.User.CharacterData) -> Project.Common.CharacterDetailModel
M Project.Common.CharacterDetailModel	CreateFromMaster(Project.Master.MasterDataStore,System.Int64,System.Int32,System.Int32,System.Boolean) -> Project.Common.CharacterDetailModel
P Project.User.CharacterData	ParameterData : Project.User.CharacterParameterData
P Project.User.CharacterParameterData	Lv : System.Int32
P Project.User.CharacterData	LimitBreakCount : System.Int32
# UserData 工厂从账号能力记录建模；Master 工厂只按角色 Master、突破与只读技能等级建模
ISIL CharacterDetailModel.txt:1567 CharacterAbilityModel.CreateByTableId(masterDataStore,userData,character.Id,token)
ISIL CharacterDetailModel.txt:1843 CharacterAbilityModel.CreateByMasterId(masterDataStore,character.MCharaId,character.LimitBreakCount,isMaxAbilityLv,token)
ISIL CharacterDetailModel.txt:1837 SkillDescriptionModel.CreateModel(mCharacter.id,limitBreakCount,isMaxAbilityLv)
P Project.Outgame.AbilityModel	LoadThumbnail : Project.Outgame.LazyLoadThumbnail
M Project.Outgame.AbilityModel	GetDescription() -> System.String
M Project.CharacterDetail.CharacterAbilityUpInfoBoxViewService	UpdateView(Project.Common.CharacterDetailModel) -> System.Void
P Project.CharacterDetail.CharacterAbilityUpInfoBoxViewService	_abilityUpButton : Project.AppButton
P Project.CharacterDetail.CharacterAbilityUpInfoBoxViewService	_resetButton : Project.AppButton
P Project.CharacterDetail.CharacterAbilityUpInfoBoxViewService	_abilityUpInformationViewList : Il2CppSystem.Collections.Generic.List<Project.CharacterDetail.CharacterAbilityUpInformationView>
P Project.CharacterDetail.CharacterAbilityUpInformationView	_unlockButton : Project.AppButton
P Project.CharacterDetail.CharacterAbilityUpInformationView	_fluctuationButtonGroup : Project.Outgame.FluctuationButtonGroup
M Project.CharacterDetail.CharacterAbilityUpInfoBoxViewService+__c	_InitializeViewAsync_b__15_1(UniRx.Unit,Project.CharacterDetail.CharacterAbilityUpInfoBoxViewService) -> System.Void
M Project.CharacterDetail.CharacterAbilityUpInfoBoxViewService+__c__DisplayClass33_0	_OpenUnlockConfirmPopupAsync_b__0() -> System.Void
# 同步点击闭包仅启动升级/解锁异步流程；在这里 return false 可在进入 UniTask/RequestAsync 前拦截
ISIL CharacterAbilityUpInfoBoxViewService_NestedType___c.txt:1005-1020 _InitializeViewAsync_b__15_1 -> OpenEnhanceConfirmPopupAsync state machine -> Forget
ISIL CharacterAbilityUpInfoBoxViewService_NestedType___c__DisplayClass33_0.txt _OpenUnlockConfirmPopupAsync_b__0 -> UnlockAbilityAsync path
M Project.Interaction.AdventurerDetail.StoryListThumbnail	UpdateView(Project.Interaction.AdventurerDetail.StoryListThumbnailModel,System.Int32) -> System.Void
P Project.Interaction.AdventurerDetail.StoryListThumbnailModel	_IsExistStory_k__BackingField : System.Boolean
# 普通 StoryListViewController 使用 StoryListThumbnail；R18StoryListViewController 使用独立的 StoryListPictThumbnail
M Project.Interaction.AdventurerDetail.StoryListViewController	UpdateListView(Il2CppSystem.Collections.Generic.IEnumerable<MNovelCharacters>,System.Int32) -> System.Void
# 普通个人剧情由 MNovelCharacters 动态 condition_value 与当前羁绊比较构造，不依赖硬编码 1/5/15 列表
ISIL StoryListViewController_NestedType___c__DisplayClass9_0.txt:92-107 intimacyLevel >= condition_value -> StoryListThumbnailModel.IsExistStory
ISIL AdventurerDetail.SubService.txt:115 OpenConfirmEventStoryPopupAsync(same StoryListThumbnailModel)
M Project.Interaction.ProfileMode.ProfileReplayViewController	UpdateView(Il2CppSystem.Collections.Generic.List<ProfileReplayListModel>,Il2CppSystem.Collections.Generic.List<ProfileReplayListModel>,Project.User.CharacterData) -> System.Void
P Project.Interaction.ProfileMode.ProfileReplayListModel	IsLocked : System.Boolean
# eventList 在 CreateList 前保存；点击只依据 IsLocked 分流到本地演出或锁定提示
ISIL ProfileReplayViewController.txt:641,665 UpdateView eventList -> this._eventList -> CreateList
ISIL ProfileReplayViewController.txt:1192 voiceList.Concat(this._eventList)
ISIL ProfileReplayViewController_NestedType___c__DisplayClass15_0.txt:437-816 IsLocked=false -> OpenNovelPopup/Prize/Cast; IsLocked=true -> OpenHint
PROXY/ISIL ProfileReplayViewController contains no ApiDataStore.RequestAsync

## 未持有角色交流页缩略图加载接缝（Project.dll 代理源码 + ISIL + Player.log，2026-08-26）
class Project.ThumbnailLoader.CharacterThumbnailLoader
M Project.ThumbnailLoader.CharacterThumbnailLoader LoadThumbnailFromUserDataAsync(Project.AppDefine+IconSize,System.Int64,Project.Master.SkinType,Absf.CacheType) -> Cysharp.Threading.Tasks.UniTask`1[[UnityEngine.Sprite, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]
M Project.ThumbnailLoader.CharacterThumbnailLoader LoadThumbnailFromMasterDataAsync(Project.AppDefine+IconSize,System.Int64,Project.Master.SkinType,Absf.CacheType) -> Cysharp.Threading.Tasks.UniTask`1[[UnityEngine.Sprite, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]
# UserData 路径直接枚举 loader._characterDataStore 的账号角色列表，按 MCharaId FirstSafe
ISIL CharacterThumbnailLoader_LoadThumbnailFromUserDataAsync:379-389 Func<CharacterData,bool> + FirstSafe
ISIL CharacterThumbnailLoader_LoadThumbnailFromUserDataAsync:401-440 CharacterData skin id -> MCharacterSkins.Get
# MasterData 路径不读取 CharacterData，直接按 (mCharacterId,skinType) 查 MCharacterSkins
ISIL CharacterThumbnailLoader_LoadThumbnailFromMasterDataAsync:304-321 ValueTuple<Int64,Int32> -> MRecordCache.Get
# 交流页模式切换和 CreateBg 都调用 UserData 路径；真实异常栈由 SwitchChara 进入该加载器
ISIL AdventurerDetail.SubService.SwitchChara:2369 LoadThumbnailFromUserDataAsync
ISIL AdventurerDetail.SubService.CreateBg:5008 LoadThumbnailFromUserDataAsync
Player.log: FirstSafe -> CharacterThumbnailLoader.LoadThumbnailFromUserDataAsync -> AdventurerDetail.SubService.SwitchChara
""";
}
