// <auto-generated by fixture-embed> 内嵌自 evidence/fixtures/proxy-targets.tsv（新鲜反编译提取，2026-08-26）。
// 目的：让测试完全自包含，不依赖仓库外的 evidence/ 大文件。
namespace AbyssCGUnlock.Tests;

internal static class ProxyTargetsFixture
{
    internal const string Text = """
# 新鲜代理程序集(Project.dll)元数据夹具 —— 由 evidence/dump/types.tsv + members.tsv + ISIL 提取
# 提取: docker run --rm -v evidence:/e:ro debian:bookworm-slim grep ... (2026-08-26)

## 类型（types.tsv 原文）
class	Project.Interaction.AdventurerDetail.R18StoryListViewController	base=Project.Common.Scroller.SimpleListViewServiceBase`1[[Project.Interaction.AdventurerDetail.StoryListPictThumbnail, Project, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]
class	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	base=Il2CppSystem.Object
class	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	base=UnityEngine.MonoBehaviour
class	Project.Interaction.AdventurerDetail.StoryListThumbnailModel	base=Il2CppSystem.Object
enum	Project.Master.NovelType	base=System.Enum

## 成员（members.tsv 原文，注意代理名称已被改写）
M	Project.Interaction.AdventurerDetail.R18StoryListViewController	UpdateListView(Il2CppSystem.Collections.Generic.IEnumerable`1[[Project.Master.NoaMessagePack.MNovelCharacters, Project, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]],Il2CppSystem.Collections.Generic.IEnumerable`1[[Project.Master.NoaMessagePack.MNovelCharacterSkins, Project, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]],System.Int32,Il2CppSystem.Collections.Generic.List`1[[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]],System.Boolean) -> System.Void
M	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	UpdateView(Project.Interaction.AdventurerDetail.StoryListThumbnailModel) -> System.Void
P	Project.Interaction.AdventurerDetail.StoryListThumbnailModel	_IsExistStory_k__BackingField : System.Boolean
P	Project.Interaction.AdventurerDetail.StoryListThumbnailModel	_IsNtr_k__BackingField : System.Boolean
P	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	_coverObject : UnityEngine.GameObject
P	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	_coverText : TMPro.TMP_Text
P	Project.Interaction.AdventurerDetail.StoryListPictThumbnail	_ntrBlockObject : UnityEngine.GameObject
M	Project.Interaction.AdventurerDetail.StoryListThumbnailModel	get_NovelType() -> Project.Master.NovelType
M	Project.Interaction.AdventurerDetail.R18StoryListViewController	get_ActiveModels() -> Il2CppSystem.Collections.Generic.IReadOnlyList`1[[Project.Interaction.AdventurerDetail.StoryListThumbnailModel, Project, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]

## NovelType 枚举成员（members.tsv）
F	Project.Master.NovelType	None : Project.Master.NovelType
F	Project.Master.NovelType	Main : Project.Master.NovelType
F	Project.Master.NovelType	Event : Project.Master.NovelType
F	Project.Master.NovelType	Character : Project.Master.NovelType
F	Project.Master.NovelType	Home : Project.Master.NovelType
F	Project.Master.NovelType	CharacterSkin : Project.Master.NovelType
F	Project.Master.NovelType	Prologue : Project.Master.NovelType
F	Project.Master.NovelType	Other : Project.Master.NovelType
## ISIL 证据: 构造器 NovelType 赋值
ISIL StoryListThumbnailModel.txt:235 Move NovelType,3 (MNovelCharacters 构造器)
ISIL StoryListThumbnailModel.txt:423 Move NovelType,5 (MNovelCharacterSkins 构造器)
## 闭包方法在代理程序集里的真实（改写后）名字
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	_UpdateListView_b__0(Project.Master.NoaMessagePack.MNovelCharacters) -> Project.Interaction.AdventurerDetail.StoryListThumbnailModel
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	_UpdateListView_b__1(Project.Master.NoaMessagePack.MNovelCharacterSkins) -> Project.Interaction.AdventurerDetail.StoryListThumbnailModel
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	get_intimacyLevel() -> System.Int32
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	set_intimacyLevel(System.Int32) -> System.Void
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	get___4__this() -> Project.Interaction.AdventurerDetail.R18StoryListViewController
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	set___4__this(Project.Interaction.AdventurerDetail.R18StoryListViewController) -> System.Void
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	get_userSkinIds() -> Il2CppSystem.Collections.Generic.List`1[[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
M	Project.Interaction.AdventurerDetail.R18StoryListViewController+__c__DisplayClass11_0	set_userSkinIds(Il2CppSystem.Collections.Generic.List`1[[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]) -> System.Void
## 代理程序集类型声明可见性（ilspycmd 反编译原文）
public sealed class __c__DisplayClass11_0 : Il2CppSystem.Object  [ObfuscatedName(...

## 190103/190108 服务端校验证据（2026-08-26 追加）
# 播放确认后的服务端请求（ISIL ConfirmNovelFlashbackPopupController_NestedType___TransitionNovelScene_b__16_0_d.txt:392）
Call NovelApiDataStore.RequestAsync, NovelReadResponseEntity, this._novelType, this._novelId
# 错误码展示层（ISIL ApiErrorMessageBuilder.txt:554）
String.Format, Error: エラーが発生しました。Error Code: {0}, errorCode
# 错误码映射（dump types.tsv/members.tsv）
class  Project.Api.ServerErrorCode  (ServerErrorCodeMap: Dictionary Int32,String)
M  Project.Api.NovelApiDataStore  RequestAsync(Project.Master.NovelType,System.Int64,Il2CppSystem.Threading.CancellationToken)
F  Project.Api.NovelApiDataStore  NativeMethodInfoPtr_RequestAsync_Public_Static_UniTask_1_NovelReadResponseEntity_NovelType_Int64_CancellationToken_0
class  Project.Api.NovelReadResponseEntity  base=Project.Api.AppContentsEntityBase
P  Project.Api.NovelReadResponseEntity  read_rewards
class  Project.Api.RecordEntity / Project.Api.NotifyEntity  (AppContentsEntityBase.records/notifies)
# ui_misc 主数据文本（AbyssMod dump，只读）
逆夜袭玩法套餐 / Error Code: 190108
和老师一起的培训 / Error Code: 190103
""";
}
